### ISSUE TITLE
SyntaxError during npm run dev/build

### ISSUE THREAD

**Issue by artofvs** [michalzaq12/electron-nuxt#34]
`npm run dev/build` logs SyntaxError in console, but I'm not sure if it affects app in any way. Template code seems to be running as it should. Tried different settings when initializing template, but it doesn't seem to be related to any of them.
System: Windows 7 x64

``` shell
λ npm run dev

> electron-nuxt-test@0.0.1 dev D:\code\electron-nuxt-test
> cross-env-shell NODE_ENV=development node .electron-nuxt/index.js

         | Electron-nuxt: starting development env...{ SyntaxError: Unexpected token (2:67)
    at Parser.pp$4.raise (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2828:15)
    at Parser.pp.unexpected (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:689:10)
    at Parser.pp.expect (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2313:38)
    at Parser.pp$3.parseExprAtom (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2232:43)
    at Parser.pp$3.parseExprSubscripts (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2091:21)
    at Parser.pp$3.parseMaybeUnary (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2068:19)
    at Parser.pp$3.parseExprOps (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:2012:21)
    at Parser.pp$3.parseMaybeConditional (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:1995:21)
    at Parser.pp$3.parseMaybeAssign (D:\code\electron-nuxt-test\node_modules\acorn\dist\acorn.js:1970:21) pos: 69, loc: Position { line: 2, column: 67 }, raisedAt: 70 }

  Main
│  Hash: d307f8a232d30f53ff0f
│  Version: webpack 4.35.3
│  Time: 892ms
│  Built at: 2019-07-16 15:56:06
│     Asset      Size  Chunks             Chunk Names
│  index.js  63.4 KiB    main  [emitted]  main
│  Entrypoint main = index.js
│  [./.electron-nuxt/config.js] 644 bytes {main} [built]
│  [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {main} [built]
│  [./node_modules/electron-debug/index.js] 2.67 KiB {main} [built]
│  [./node_modules/electron-is-accelerator/index.js] 849 bytes {main} [built]
│  [./node_modules/electron-is-dev/index.js] 281 bytes {main} [built]
│  [./node_modules/electron-localshortcut/index.js] 8.16 KiB {main} [built]
│  [./node_modules/electron-localshortcut/node_modules/debug/src/index.js] 263 bytes {main} [built]
│  [./node_modules/keyboardevent-from-electron-accelerator/index.js] 6.04 KiB {main} [built]
│  [./node_modules/vue-devtools/lib/index.js] 1.35 KiB {main} [built]
│  [./src/main/BrowserWinHandler.js] 2.09 KiB {main} [built]
│  [./src/main/index.dev.js] 861 bytes {main} [built]
│  [./src/main/index.js] 442 bytes {main} [built]
│  [./src/main/mainWindow.js] 642 bytes {main} [built]
│  [electron] external "electron" 42 bytes {main} [built]
│  [path] external "path" 42 bytes {main} [built]
│      + 10 hidden modules
│
│  WARNING in ./node_modules/electron-debug/index.js 96:45-58
│  Critical dependency: the request of a dependency is an expression
│   @ ./src/main/index.dev.js
│
│  WARNING in ./node_modules/electron-debug/index.js 97:61-74
│  Critical dependency: the request of a dependency is an expression
│   @ ./src/main/index.dev.js

  Nuxt
│  i Preparing project for development
│
│  i Initial build may take a while
│
│  √ Builder initialized
│
│  √ Nuxt files generated
│
│  i Compiling Client
│
│  √ Client: Compiled successfully in 5.90s
│
│  i Waiting for file changes
│
         √ Electron-nuxt: Done

  Electron
│  Debugger l
│  istening on ws://127.0.0.1:5858/6623a9d2-a829-4ab5-a38a-8c8b12ed5647
│  For help, see: https://nodejs.org/en/docs/inspector
│
│  Installing Vue.js devtools from node_modules\vue-devtools\vender
│
```

**Comment by michalzaq12** [comment]
@artofvs, thanks for reporting the issue.
It seems to be some internal "webpack" error, and appears on all platforms (win, mac, linux).
I will try to solve it
