### ISSUE TITLE
throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

### ISSUE THREAD

**Issue by pengjinning** [michalzaq12/electron-nuxt#377]
ningjinpengdeMacBook-Pro:electron-nuxt ningjinpeng$ yarn install
yarn install v1.22.0
$ node .electron-nuxt/check-engines.js
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps 
  • electron-builder  version=22.6.0
✨  Done in 1.32s.
ningjinpengdeMacBook-Pro:electron-nuxt ningjinpeng$ yarn run dev
yarn run v1.22.0
$ node .electron-nuxt/dev.js
/Users/ningjinpeng/Desktop/GitOSChina/bytedeskpc/electron-nuxt/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/ningjinpeng/Desktop/GitOSChina/bytedeskpc/electron-nuxt/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Users/ningjinpeng/Desktop/GitOSChina/bytedeskpc/electron-nuxt/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ningjinpeng/Desktop/GitOSChina/bytedeskpc/electron-nuxt/.electron-nuxt/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by michalzaq12** [comment]
I can't help you, this issue is directly linked to electron, not to my template. 
There are some problems with downloading Electron in China: 
- https://github.com/electron/electron/issues/20994
- https://github.com/electron/electron/issues/8466
