### ISSUE TITLE
How to add a Preload.js File 

### ISSUE THREAD

**Issue by 19peaches** [michalzaq12/electron-nuxt#762]
I need to have `nodeIntegration: false` and `contextIsolation: true` and have my preload script loaded.

I'm moving my app over from a `vue/cli` app to Nuxt, and in my old app this wasn't an issue since I could just add it to my `vue.config.js` file like so:

```
module.exports = {
  assetsDir: "assets",
  runtimeCompiler: true,

  pluginOptions: {
    electronBuilder: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: "src/preload.js",
    },
    autoRouting: {
      chunkNamePrefix: "page-",
    }
  }
}
```

I've set nodeIntegration and contextIsolation in my `BrowserWinHandler.js` file and also added a preload var:

```
preload: path.join(__dirname, 'preload.js')
```

But it's not getting compiled and added to the stack.

Thanks

**Comment by michalzaq12** [comment]
Add preload script to `src/main` directory.
Then try to use `preload: path.resolve(__dirname, 'preload.js')`

**Comment by 19peaches** [comment]
This produces a host of other errors:

```
Unable to load preload script: /Users/vince/Sites/project/client/src/main/preload.js

(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import { contextBridge, ipcRenderer } from "electron"
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at wrapSafe (internal/modules/cjs/loader.js:974:15)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)

Uncaught ReferenceError: require is not defined
    at eval (external "querystring"?30c6:1)
    at Object.querystring (app.js:800)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Object.eval (client.js?769e:18)
    at eval (client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client:308)
    at Object../node_modules/webpack-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client (app.js:683)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Object.0 (app.js:787)
```

At least it's trying to load now which is a step in the right direction.

**Comment by michalzaq12** [comment]
I forgot that you still need to change webpack target to `web` (instead of `electron-renderer`).
https://github.com/michalzaq12/electron-nuxt/blob/master/template/.electron-nuxt/renderer/nuxt.config.js#L32

**Comment by 19peaches** [comment]
Nope.

Same errors prevail. No change.

**Comment by 19peaches** [comment]
Sorry, I misspoke there.

The second error, the require not defined error is gone, but the others prevail.

**Comment by 19peaches** [comment]
Ok I changed the imports to a require instead in preload.js seems to load now.

```
const { contextBridge, ipcRenderer } = require("electron")
```

Where would be the best place to put my IPC communication?

Looking around I was thinking in `main/index.js` just before the require of `mainWindow` or does it need to come later?
