### ISSUE TITLE
Nuxt pages don't load if contextIsolation = true

### ISSUE THREAD

**Issue by azmatzuberi** [michalzaq12/electron-nuxt#916]
I'm having some trouble with enabling contextIsolation because the webpages don't load with it on.

This is what I have:
```
const winHandler = new BrowserWinHandler({
    height: 415,
    width: 550,
    movable: true,
    title: 'VIKS',
    webPreferences: {
      transparent: true,
      enableRemoteModule: false,
      contextIsolation: true,
      devTools: true,
      preload: path.resolve(__dirname, 'preload.js')
    }
  })
```

The error that I get is:

```
Uncaught ReferenceError: require is not defined
    at eval (external "querystring"?30c6:1)
    at Object.querystring (app.js:356)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Object.eval (client.js?1b93:18)
    at eval (client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client:308)
    at Object../node_modules/webpack-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client (app.js:311)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Object.0 (app.js:343)
```

This makes it hard to develop further because IPC can't be used.

**Comment by hamidrezabstn** [comment]
hi @azmatzuberi 
how you fix this problem ? 
i have similar issue!
```
Uncaught ReferenceError: require is not defined
    at eval (webpack-internal:///core-js/modules/es.array.iterator.js:1:18)
    at Object.core-js/modules/es.array.iterator.js (app.js:1664:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (webpack-internal:///./src/renderer/.nuxt/client.js:5:94)
    at Module../src/renderer/.nuxt/client.js (app.js:587:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at Object.0 (app.js:1564:18)
    at __webpack_require__ (runtime.js:854:30)
```
